version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html/"
    ports:
      - "8000:80"
      - "3000:443"
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    image: php:8.3-fpm
    restart: always
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:${DB_VERSION}
    container_name: ${DB_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./docker/db/mysql:/var/lib/mysql"